---
- name: Update Debian/Ubuntu servers
  hosts: haproxy,k3s-server
  remote_user : "marc_cg"
  become: true
  become_user: root
  # ansible_user: "marc_cg"
  # ansible_become: yes
  # ansible_become_method: sudo
  # ansible_python_interpreter: "/usr/bin/env python3"
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        upgrade: true
        cache_valid_time: 3600

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
          - git
          - htop
          - curl
          - jq
          - qemu-guest-agent
          - nfs-common
          - containerd

    - name: Check if reboot required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot the box if kernel updated
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists == true
